apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
spec:
  selector:
    matchLabels:
      app: express-app
  replicas: 1
  template:
    metadata:
      labels:
        app: express-app
        env: development
    spec:
      containers:
      - name: express-app
        image: gcr.io/securicam-351906/express-server:v1
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: express-app    
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: express-app-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 4000
#     protocol: TCP
#   selector:
#     app: express-app